In [2]:
#list 

#날짜 및 시간과 관련한 패키지
import datetime

li = range(1, 1000000)

# 현재 시간을 저장
start = datetime.datetime.now()

#모든 요소에 10을 곱하기
for i in li :
    i * 10 

# 현재 시간을 저장
end = datetime.datetime.now()
print(start, end)

# 결과 : 2024-02-06 12:35:09.259843 2024-02-06 12:35:09.382838

2024-02-06 12:35:09.259843 2024-02-06 12:35:09.382838


In [3]:
# ndarray

import numpy as np
ar = np.arange(1, 1000000)


# 현재 시간을 저장
start = datetime.datetime.now()

#모든 요소에 10을 곱하기
ar = ar * 10

# 현재 시간을 저장
end = datetime.datetime.now()
print(start, end)

# 결과 : 2024-02-06 12:37:13.530259 2024-02-06 12:37:13.530259
# 빠르다

2024-02-06 12:37:13.530259 2024-02-06 12:37:13.530259


In [5]:
import time

# 리스트 연산 속도
a = list(range(10 ** 8))

start = time.time()
for i in range(10 ** 8):
    a[i] *= 2
end = time.time()
print(end - start) # 약 17.35초

# 어레이 연산 속도
a = np.array(range(10 ** 8))

start = time.time()
a = a * 2
end = time.time()
print(end - start) # 약 1.35초

16.75233483314514
0.1751112937927246


In [8]:
#배열의 생성과 정보 확인

import numpy as np # numpy라는 모듈을 np라는 이름으로 가져와서 사용

ar = np.array([1,2,3]) # list를 이용해서 nadarray를 생성

#ndim은  몇 차원인지 확인
print(ar.ndim)

# shape은 각 차언의 데이터 개수를 튜플로 리턴
print(ar.shape)


# 2차원
table= np.array([[1,2,3],[4,5,6]]) # list를 이용해서 nadarray를 생성

#ndim은  몇 차원인지 확인
print(table.ndim)

# shape은 각 차언의 데이터 개수를 튜플로 리턴
print(table.shape)

1
(3,)
2
(2, 3)


In [10]:
print(table.dtype)

int32


In [11]:
image = np.array([[[1,2,3,],[1,2,3]],[[4,5,6],[7,8,9]]])
print(image.ndim)
print(image.shape)

3
(2, 2, 3)


In [15]:
#1부터 10까지 홀수를 가진 배열을 생성

ar = np.arange(1, 10, 2)
print(ar)

[1 3 5 7 9]


In [18]:
# 의미 없는 값으로 배열을 생성
ar = np.empty (10)
print(ar)

[nan  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [20]:
#주대각선 방향이 1 인 3*3 정방 행렬을 생성

ar = np.eye(3)
print(ar)

#행렬에서 주 대긱산의 데이터만 골라서 배열을 생성
print(np.diag(ar))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 1. 1.]


In [24]:
#데이터 티입 확인과 형 변환
ar = np.array([1, "2", 3]) # 숫자와 문자열을 가지고 배열 생성 - 문자열
print(ar.dtype)

br = np.array([1, 2.3 ,5]) # 정수와 실수 혼합 - 실수
print(br.dtype)

# ar 배열의 자료형을 정수로 변환
cr = ar.astype(np.int32)
print(cr.dtype)


<U11
float64
int32


In [31]:
# 0부터 19까지 숫자를 가지고 1차원 배열 생성
ar = np.arange(20)
print(ar)

#ar을 4*5으로 2차원 배열로 변환
matrix = ar.reshape((4, 5))
print(matrix)

# 5대신 -1을 대입해도 결과는 동일
# 20개의 데이터는 4행으로 만들려면 5열밖에 안 생김
matrix = ar.reshape(4, -1)
print(matrix)

# 다차원 데이터를 1차원으로 변환
br = matrix.reshape(-1)
br = matrix.flatten() # 똑같은 표현
print(br)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [32]:
# 배열에서 하나의 요소 접근
ar = np.arange(10)
matrix = ar.reshape((2, -1))

# 일차원 배열에 요소 접근
print(ar[0]) # 첫 번째 데이터
print(ar[-1], "\n") # 두 번째 데이터

print(matrix[0, 2])
print(matrix[0][2])

0
9 

2
2


In [34]:
# 배열에서 범위를 이용한 접근
ar = np.arange(10)
matrix = ar.reshape((2, -1))

print(ar[1:4]) # 1, 2, 3
print(ar[5:]) # 5, 6, 7, 8, 9
print(ar[:4]) # 0, 1, 2, 3
print(ar[:]) # 0, 1, 2, 3, 4, 5, 6, 7, 8, 9

# 이차원 배열에서의 접근
print(matrix[1][1:3]) # 1행의 2,3번
print(matrix[1]) # 1행 전체
print(matrix[:, 1]) # 1열 전체

[1 2 3]
[5 6 7 8 9]
[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]
[6 7]
[5 6 7 8 9]
[1 6]


In [36]:
# 배열 생성
ar = np.arange(10)
print(ar)
#범위를 이용해서 데이터를 가져오는 것 - 참조를 복사
br = ar[0:4].copy() # ar을 복사해서 br에 저장
print(br)
#br[0] 을 수정하면 ar의 데이터도 영향을 받게 됩니다.
br[0] = 42
print(br)
print(ar)# ar은 영향을 안 받아요!

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3]
[42  1  2  3]
[0 1 2 3 4 5 6 7 8 9]


In [37]:
ar = np.arange(10)

#Fancy Indexing
br = ar[[1, 3, 5, 7]]
print(br)
br[0] = 15790

print(br)
print(ar)

[1 3 5 7]
[15790     3     5     7]
[0 1 2 3 4 5 6 7 8 9]


In [40]:
matrix = ar.reshape((2, -1))
print(matrix)

print(matrix[ :, 0])
#이차원 배열에서 list를 이용해서 행 번호나 열 번호를 지정하면 이차원 배열이 만들어집니다.
print(matrix[ :, [0]])

#numpy 의 ndarray 나 pandas 의 DataFrame에서
#하나의 열을 선택할 때 list로 설정하는 경우는 구조를 유지하기 위해서입니다.


[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 5]
[[0]
 [5]]


In [44]:
print(bool([1,2,3] and [4, 5, 6]))
print(bool([1,2,3] and []))


True
False


In [48]:
#이차원 배열
matrix = ar.reshape((2, -1))

#브로드캐스트 연산
#차원이 다른 경우 차원을 순회하면서 연산을 수행
print(matrix + 10)

data = np.array([100, 200, 300, 400, 500]) # 열 수를 맞춰야 한다
print(matrix + data)

[[10 11 12 13 14]
 [15 16 17 18 19]]
[[100 201 302 403 504]
 [105 206 307 408 509]]


In [52]:
print(matrix)
print(ar)

# 브로드캐스트 연산
#numpy 의 ndarray 와 논리 연산을 수행하면 bool 배열이 만들어집니다.
print(ar == 3)
# 인덱스에 불 배열을 대입하면 True인 데이터만 추출됩니다.
print(ar[ar % 2 == 1])# 이러면 ar [True인 것들만] 추출된다.

# 두개의 조건을 결합하는 경우
# print(ar[ar % 2 == 1] or ar[ar % 4 == 0])
print(ar[(ar % 2 == 1) | (ar % 4 == 0)]) # 홀수 이면서 4의 배수인 것
# 참고! 확률이 더 높은 것을 왼쪽에 두세요!

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[False False False  True False False False False False False]
[1 3 5 7 9]
[0 1 3 4 5 7 8 9]
