In [5]:
import numpy as np

# return 유무 - def
def add(n:int) -> None :
    n + 10
    
result = add(10)
print(result)


def add(n:int) -> int :
    return n+ 10
    
result = add(10)
print(result)


# return 유무 -lambda
f = lambda i : i +10
print(f(10))

None
20
20


In [8]:
matrix = np.array([1, 2, 3])

# 요소의 제곱을 수행하는 람다 함수
square_lambda = lambda x : x*x

#함수를 배열의 모든 요소에 적용해서 결과를 배열로 만들기
vectorized_func = np.vectorize(square_lambda)
reslut = vectorized_func(matrix)

print(result)

20


In [14]:
#데이터가 None이면0, 100보다 크면 100으로 한 결과 배열 생성
ar = np.array([80, 70, 80, None, 120])

#None(결측치)를 걸러내는 작업을 먼저 해야 합니다.
# None과 >100의 순서를 바꾸면 에러가 납니다.
def preprocessing(data) -> int:
    if data ==None :
        return 0
    elif data > 100 :
        return 100
    else :
        return data
    
vec_func = np.vectorize(preprocessing)zf7,k
print(vec_func(ar))

[ 80  70  80   0 100]


In [16]:
# 행렬의 전치 -축변경
original = np.array([[1,2,3], [4,5,6]])

print(original)
print(original.T)
print(original.transpose(1, 0))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [20]:
# 랜덤한 숫자 추출의 개념

#seed를 고정하지 않으면 실행 시간을 기준으로 seed가 설정되므로
#실행할 때 마다 다른 숫자가 리턴
result  = np.random.normal(size = 5)
print(result)


#seed 를 42로 고정하면 실행할 때마다 동일한 데이터가 리턴됩니다.
#머신러닝에서는 일반적으로 seed를 고정!
np.random.seed(seed = 42)
result= np.random.normal(size = 5)
print(result)

[-0.23413696  1.57921282  0.76743473 -0.46947439  0.54256004]
[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]


In [24]:
#help(np.random.randint)
# 위의 함수를 이용해서 1 ~46까지의 숫자 6개를 출력

tmp = np.random.randint(low=1, high=47, size=6)
print(tmp)

[ 3 22  2 24 44 30]


In [29]:
matrix = np.arange(1, 13).reshape((4, -1))
print(matrix) # 전체 합
print(np.sum(matrix, axis = 0)) # 열방향으로 합
print(np.sum(matrix, axis = 1)) # 행방향으로 합

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[22 26 30]
[ 6 15 24 33]


In [33]:
# 피보나치 수열
def fibo(n:int) -> int :
    if n == 1 or n ==2 :
        return 1
    else :
        return fibo(n-1) + fibo(n-2)
print(fibo(6))

def norecursion_fibo(n:int)-> int :
    n1 = 1
    n2 = 1
    v = 1
    for i in range(3, n+1) :
        v = n1 + n2
        n2 = n1
        n1 = v 
        return v
    
print(norecursion_fibo(6))

8
2


In [34]:
#표준 편차와 분산은 ddof옵션에 따라 값이 다르게 나옵니다.
#표준 편차와 분산은 평균이라는 통계값을 가지고 구하게 되는데
#평균이 결정되면 전체 데이터 개수 -1 만큼의 값을 알게되면
#나머지 1개의 값은 자동을 정해지게 되는데  이를 자유도라고 하고
#이를 빼고 계산하거나, 포함 시켜서 계산하는 옵션 ddof 입니다.
# 1, 2, 3
print(np.var(matrix))
print(np.var(matrix,ddof =1))

11.916666666666666
13.0


In [35]:
print(np.cumsum(matrix))
print(np.cumsum(matrix, axis = 0))

[ 1  3  6 10 15 21 28 36 45 55 66 78]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]
 [22 26 30]]


In [37]:
#numpy.isnan(배열) : 배열에 None, Null등이 포함여부를 리턴
#None을 numpy.nan으로 표현
#logical_not 함수는  조건에 맞지 않는 데이터인지 여부를 리턴

import numpy as np

# 배열 생성
ar = np.array([10, 2, 3, 4, np.nan, 32, 42])

# 배열에 None 데이터가 있는지 확인
print(np.isnan(ar)) # 결측치 확인

# 결측치를 제외하고 가져오기
# 보통 None이 아닌 것보다 None인 것을 가져오는 게 더 빠름
result = ar[np.logical_not(np.isnan(ar))]
print(result)

# 결측치를 제외하고 가져오기 - 결측치를 제거하지 않고 수행하면 nan이 포함됨
#ar를 가지고 수행하면 np.nan이 포함되고 result를 가지고 수행하면 np.nan
result = ar[np.logical_not(ar > 10)]
print(result)

[False False False False  True False False]
[10.  2.  3.  4. 32. 42.]
[10.  2.  3.  4. nan]


In [42]:
ar = np.array([2, 5, 23, 34, 21, 42, np.nan, 25])
print(ar)

#3의 배수이거나 4의 배수인 데이터만 추출 np.nan을 제거
tmp = ar[np.logical_not(np.isnan(ar))]
result = tmp[(tmp % 4 == 0) | (tmp % 3 ==0)]
print(result)

[ 2.  5. 23. 34. 21. 42. nan 25.]
[21. 42.]


In [43]:
#아래 데이터는 1,2 3, 4 중에 하나를 선택하는 범주형 데이터의 집합
#이상한 값이 있는지 확인- 혼자만 엄청 큰 값이 나온다면 계는 이상치
ar = np.array([2, 1, 3, 4, 5, 1, 2, 3])
print(np.unique(ar))

[1 2 3 4 5]


In [46]:
help(np.ndarray.sort)

Help on method_descriptor:

sort(...)
    a.sort(axis=-1, kind=None, order=None)
    
    Sort an array in-place. Refer to `numpy.sort` for full documentation.
    
    Parameters
    ----------
    axis : int, optional
        Axis along which to sort. Default is -1, which means sort along the
        last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort under the covers and, in general, the
        actual implementation will vary with datatype. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A single field can
        be specified as a string, and not all fields need be 

In [53]:
# 
ar = np.array([2, 1, 3, 4, np.nan])
print(ar.sort()) # return 값이 없기 떄문에 sort를 print하면 None이 나온당
print(ar) # 대신return이 없는 경우는 원본테이터가 바뀐다.
# numpy의 sort는 return을 하고, ndarray의 sort는 return하지 않습니다.
#내림차순 정렬은 numpy의 sort를 이용하면 됩니다.
print(np.sort(ar)[::-1]) 

#2차원 배열은 numpy에서는 sort를 잘 사용하지 않습니다.
#데이터의 인덱스가 깨져버립니다.
matrix = np.array([[1, 3, 5, 2], [4, 6,2, 9]])
print(matrix)
matrix.sort(axis = 0)
print(matrix)

None
[ 1.  2.  3.  4. nan]
[nan  4.  3.  2.  1.]
[[1 3 5 2]
 [4 6 2 9]]
[[1 3 2 2]
 [4 6 5 9]]


In [61]:
#hstack
ar = np.array([[1, 2, 3], [4, 5, 6]])
print(ar)

br = np.array([[11, 22, 33], [44, 55, 66]])
print(br)

print()

print(np.hstack([ar, br]))
print(np.vstack([ar, br]))

tmp = np.vstack([ar, br])
print(tmp.shape)


[[1 2 3]
 [4 5 6]]
[[11 22 33]
 [44 55 66]]

[[ 1  2  3 11 22 33]
 [ 4  5  6 44 55 66]]
[[ 1  2  3]
 [ 4  5  6]
 [11 22 33]
 [44 55 66]]
(4, 3)


In [62]:
#help(np.savez)

Help on function savez in module numpy:

savez(file, *args, **kwds)
    Save several arrays into a single file in uncompressed ``.npz`` format.
    
    Provide arrays as keyword arguments to store them under the
    corresponding name in the output file: ``savez(fn, x=x, y=y)``.
    
    If arrays are specified as positional arguments, i.e., ``savez(fn,
    x, y)``, their names will be `arr_0`, `arr_1`, etc.
    
    Parameters
    ----------
    file : str or file
        Either the filename (string) or an open file (file-like object)
        where the data will be saved. If file is a string or a Path, the
        ``.npz`` extension will be appended to the filename if it is not
        already there.
    args : Arguments, optional
        Arrays to save to the file. Please use keyword arguments (see
        `kwds` below) to assign names to arrays.  Arrays specified as
        args will be named "arr_0", "arr_1", and so on.
    kwds : Keyword arguments, optional
        Arrays to save

In [63]:
#데이터 저장
np.save('ar.npy',ar)

In [65]:
# 데이터 로드
x = np.load('ar.npy')
print(x)

[[1 2 3]
 [4 5 6]]


In [68]:
# pandas
import pandas as pd 

In [72]:
price = pd.Series([1000, 2000, 3000, 4000])
print(price)
print(price[1])

print()

price.index = ['사탕', '과자', '음료수', '과일']
print(price)
print(price['사탕'])

0    1000
1    2000
2    3000
3    4000
dtype: int64
2000

사탕     1000
과자     2000
음료수    3000
과일     4000
dtype: int64
1000


In [77]:
x = price['사탕' : '음료수'] # 사탕부터 음료수까지
x['사탕'] = 800
print(x)
print(price) # x와 price의 주소를 참조해서 변경하면 같이 바뀜
print()

y = price[['사탕', '음료수']] # 사탕과 음료수
y['사탕'] = 2000
print(y)
print(price) # 사탕과 음료수의 데이터를 복제해 온 것 즉 변경이 되지 않음!

사탕      800
과자     2000
음료수    3000
dtype: int64
사탕      800
과자     2000
음료수    3000
과일     4000
dtype: int64

사탕     2000
음료수    3000
dtype: int64
사탕      800
과자     2000
음료수    3000
과일     4000
dtype: int64


In [81]:
s1 = pd.Series([100, 200, 300, np.nan], index = ['사과', '배', '한라봉', '바나나'])
print(s1)
print()

s2 = pd.Series([100, 200, 300, 500], index = ['사과', '한라봉', '바나나', '딸기'])
print(s2)
print()


#시리즈는 인덱스를 일치하는 데이터끼리 연산을 수행합니다.
#한쪽에만 존재하거나 np.nan 인 데이터가 있으면 결과가 np.nan이 됩니다.
print(s1 + s2)

사과     100.0
배      200.0
한라봉    300.0
바나나      NaN
dtype: float64

사과     100
한라봉    200
바나나    300
딸기     500
dtype: int64

딸기       NaN
바나나      NaN
배        NaN
사과     200.0
한라봉    500.0
dtype: float64


In [82]:
# dataframe 생성
source = {
    "code" : [1, 2, 3, 4, 5],
    "name" : ['소연', '민니', '미연', '우기', '슈화'],
    "age" : [25, 27, 27, 25, 24]
}

df = pd.DataFrame(source)
print(df)



   code name  age
0     1   소연   25
1     2   민니   27
2     3   미연   27
3     4   우기   25
4     5   슈화   24


In [84]:
print(df.head(3)) # 앞에서 3개

   code name  age
0     1   소연   25
1     2   민니   27
2     3   미연   27


In [85]:
print(df.tail(2)) # 뒤에서 2개

   code name  age
3     4   우기   25
4     5   슈화   24


In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   code    5 non-null      int64 
 1   name    5 non-null      object
 2   age     5 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes


In [91]:
print(df.index)
print(df.values)
print(type(df.values))

RangeIndex(start=0, stop=5, step=1)
[[1 '소연' 25]
 [2 '민니' 27]
 [3 '미연' 27]
 [4 '우기' 25]
 [5 '슈화' 24]]
<class 'numpy.ndarray'>


In [97]:
# print(dir(df))
# help(df.isnull)
print(df.isnull())

    code   name    age
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
