## 데이터 전처리

### 한글 형태소 분석

In [5]:
!pip install konlpy

     ---------------------------------------- 0.0/19.4 MB ? eta -:--:--
     ---------------------------------------- 0.0/19.4 MB ? eta -:--:--
     ---------------------------------------- 0.2/19.4 MB 4.1 MB/s eta 0:00:05
     -- ------------------------------------- 1.1/19.4 MB 9.7 MB/s eta 0:00:02
     ----- ---------------------------------- 2.7/19.4 MB 17.3 MB/s eta 0:00:01
     ----------- ---------------------------- 5.6/19.4 MB 25.4 MB/s eta 0:00:01
     -------------------- ------------------ 10.4/19.4 MB 46.7 MB/s eta 0:00:01
     ------------------------------- ------- 15.7/19.4 MB 93.0 MB/s eta 0:00:01
     -------------------------------------  19.4/19.4 MB 108.8 MB/s eta 0:00:01
     --------------------------------------- 19.4/19.4 MB 65.5 MB/s eta 0:00:00
  Obtaining dependency information for JPype1>=0.7.0 from https://files.pythonhosted.org/packages/1f/19/144f3a767b563ba5c6d4aa534ea1f3fad9a5067c3917df4458a6e1afe0ef/JPype1-1.5.0-cp311-cp311-win_amd64.whl.metadata
   --

In [2]:
#형태소 분석할 문장
text = '가영이는 오늘 아침에 알람을 듣지 않고도 눈이 번쩍 떠졌지만 이내 다시 깊은 잠에 빠져들었다'

# 자연어 처리를 할 때 공백 단위로 토큰화 하는 것은 큰 의미가 없음
# 공백 단위로 토큰화 하는 것은 로그 분석을 할 때입니다.

data = text.split(' ')
print(data)


['가영이는', '오늘', '아침에', '알람을', '듣지', '않고도', '눈이', '번쩍', '떠졌지만', '이내', '다시', '깊은', '잠에', '빠져들었다']


In [8]:
from konlpy.tag import Kkma
kkma = Kkma()
#문장 분석
print(kkma.sentences(text))

#단어별 분석
print(kkma.nouns(text))

#형태소 분석 - 품사를 같이 제공 ;이 작업을 같이 수행하는 것을 품사 태깅 - 자연어 처리에 한 부분
print(kkma.pos(text))

print("====================================================")
from konlpy.tag import Hannanum

hannanum = Hannanum()
print(hannanum.nouns(text))
print(hannanum.pos(text))

print("=====================================================")
# from konlpy.tag import Okt


['가 영이는 오늘 아침에 알람을 듣지 않고도 눈이 번쩍 떠졌지만 이내 다시 깊은 잠에 빠져들었다']
['영이', '오늘', '아침', '알람', '눈', '잠']
[('가', 'VV'), ('아', 'ECS'), ('영이', 'NNG'), ('는', 'JX'), ('오늘', 'NNG'), ('아침', 'NNG'), ('에', 'JKM'), ('알람', 'NNG'), ('을', 'JKO'), ('듣', 'VV'), ('지', 'ECD'), ('않', 'VXV'), ('고', 'ECE'), ('도', 'JX'), ('눈', 'NNG'), ('이', 'JKS'), ('번쩍', 'MAG'), ('떠지', 'VV'), ('었', 'EPT'), ('지만', 'ECE'), ('이내', 'MAG'), ('다시', 'MAG'), ('깊', 'VA'), ('은', 'ETD'), ('잠', 'NNG'), ('에', 'JKM'), ('빠져들', 'VV'), ('었', 'EPT'), ('다', 'EFN')]
['가영', '오늘', '아침', '알람', '눈', '빠져들었다']
[('가영', 'N'), ('이', 'J'), ('는', 'E'), ('오늘', 'N'), ('아침', 'N'), ('에', 'J'), ('알람', 'N'), ('을', 'J'), ('듣', 'P'), ('지', 'E'), ('않', 'P'), ('고', 'E'), ('도', 'J'), ('눈', 'N'), ('이', 'J'), ('번쩍', 'M'), ('뜨', 'P'), ('어', 'E'), ('지', 'P'), ('었지만', 'E'), ('이내', 'M'), ('다시', 'M'), ('깊', 'P'), ('은', 'E'), ('자', 'P'), ('ㅁ', 'E'), ('에', 'J'), ('빠져들었다', 'N')]


### BoW(Bag of Word) 단어 별 빈도수

In [14]:
# 샘플 데이터 생성
import numpy as np
import pandas as pd

text_data = np.array(['I have a dream to dream when i fly the blue sky',
                     'My favorite color is blue and red',
                     'Korea Flag has a three kinds of color Blue , Red , Black',
                     'That blue family is blue mother , blue father , and three blue kids'])
from sklearn.feature_extraction.text import CountVectorizer

#BoW 객체를 생성
#모든 문자열을 소문자로 변경해서 수행
countVectorizer = CountVectorizer()
bag_of_words = countVectorizer.fit_transform(text_data)

#희소 행렬
print(bag_of_words)

#밀집 행렬
print(bag_of_words.toarray())

#각 열의 의미
print(countVectorizer.get_feature_names_out())

  (0, 11)	1
  (0, 4)	2
  (0, 24)	1
  (0, 25)	1
  (0, 9)	1
  (0, 22)	1
  (0, 2)	1
  (0, 20)	1
  (1, 2)	1
  (1, 17)	1
  (1, 7)	1
  (1, 3)	1
  (1, 12)	1
  (1, 0)	1
  (1, 19)	1
  (2, 2)	1
  (2, 3)	1
  (2, 19)	1
  (2, 15)	1
  (2, 8)	1
  (2, 10)	1
  (2, 23)	1
  (2, 14)	1
  (2, 18)	1
  (2, 1)	1
  (3, 2)	4
  (3, 12)	1
  (3, 0)	1
  (3, 23)	1
  (3, 21)	1
  (3, 5)	1
  (3, 16)	1
  (3, 6)	1
  (3, 13)	1
[[0 0 1 0 2 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1 1]
 [1 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 0 0 1 0 0]
 [1 0 4 0 0 1 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0 1 0 1 0 0]]
['and' 'black' 'blue' 'color' 'dream' 'family' 'father' 'favorite' 'flag'
 'fly' 'has' 'have' 'is' 'kids' 'kinds' 'korea' 'mother' 'my' 'of' 'red'
 'sky' 'that' 'the' 'three' 'to' 'when']


### 단어 별 가중치 계싼 tf-idf

In [15]:
text_data = np.array(['I have a dream to dream when i fly the blue sky',
                     'My favorite color is blue and red',
                     'Korea Flag has a three kinds of color Blue , Red , Black',
                     'That blue family is blue mother , blue father , and three blue kids'])
from sklearn.feature_extraction.text import TfidfVectorizer

tfidfVectorizer = TfidfVectorizer()
feature_matrix = tfidfVectorizer.fit_transform(text_data)

print(tfidfVectorizer.vocabulary_)
print(feature_matrix.toarray())

{'have': 11, 'dream': 4, 'to': 24, 'when': 25, 'fly': 9, 'the': 22, 'blue': 2, 'sky': 20, 'my': 17, 'favorite': 7, 'color': 3, 'is': 12, 'and': 0, 'red': 19, 'korea': 15, 'flag': 8, 'has': 10, 'three': 23, 'kinds': 14, 'of': 18, 'black': 1, 'that': 21, 'family': 5, 'mother': 16, 'father': 6, 'kids': 13}
[[0.         0.         0.16281873 0.         0.62401605 0.
  0.         0.         0.         0.31200802 0.         0.31200802
  0.         0.         0.         0.         0.         0.
  0.         0.         0.31200802 0.         0.31200802 0.
  0.31200802 0.31200802]
 [0.36141758 0.         0.23921859 0.36141758 0.         0.
  0.         0.45841237 0.         0.         0.         0.
  0.36141758 0.         0.         0.         0.         0.45841237
  0.         0.36141758 0.         0.         0.         0.
  0.         0.        ]
 [0.         0.35056235 0.18293797 0.27638738 0.         0.
  0.         0.         0.35056235 0.         0.35056235 0.
  0.         0.         0.350

In [20]:
df = pd.read_csv('./data/stock-data.csv')
# df.info()

df['NewDate'] = pd.to_datetime(df['Date'])
df.info()

print(df.head())

df.set_index("NewDate", inplace = True)
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype         
---  ------   --------------  -----         
 0   Date     20 non-null     object        
 1   Close    20 non-null     int64         
 2   Start    20 non-null     int64         
 3   High     20 non-null     int64         
 4   Low      20 non-null     int64         
 5   Volume   20 non-null     int64         
 6   NewDate  20 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(5), object(1)
memory usage: 1.2+ KB
         Date  Close  Start   High    Low  Volume    NewDate
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26
                  Date  Close  Start   High    Low  Volume

### Period를 이용한 날짜 형식 변경

In [24]:
dates = ['2024-02-20', '2000-10-14','1998-03-26']

pddates = pd.to_datetime(dates)
print(pddates)

pr_months = pddates.to_period(freq='Q')
print(pr_months)
pr_months = pddates.to_period(freq='M')
print(pr_months)

DatetimeIndex(['2024-02-20', '2000-10-14', '1998-03-26'], dtype='datetime64[ns]', freq=None)
PeriodIndex(['2024Q1', '2000Q4', '1998Q1'], dtype='period[Q-DEC]')
PeriodIndex(['2024-02', '2000-10', '1998-03'], dtype='period[M]')


### 일정한 간격을 갖는 데이터 생성

In [25]:
ts_ms = pd.date_range(start = '2024-01-01', end = None, periods = 30, freq = 'D')
print(ts_ms)

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10', '2024-01-11', '2024-01-12',
               '2024-01-13', '2024-01-14', '2024-01-15', '2024-01-16',
               '2024-01-17', '2024-01-18', '2024-01-19', '2024-01-20',
               '2024-01-21', '2024-01-22', '2024-01-23', '2024-01-24',
               '2024-01-25', '2024-01-26', '2024-01-27', '2024-01-28',
               '2024-01-29', '2024-01-30'],
              dtype='datetime64[ns]', freq='D')


In [26]:
ts_ms = pd.date_range(start = '2024-01-01', end = None, periods = 30, freq = 'M')
print(ts_ms)

DatetimeIndex(['2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30',
               '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31',
               '2024-09-30', '2024-10-31', '2024-11-30', '2024-12-31',
               '2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30', '2025-07-31', '2025-08-31',
               '2025-09-30', '2025-10-31', '2025-11-30', '2025-12-31',
               '2026-01-31', '2026-02-28', '2026-03-31', '2026-04-30',
               '2026-05-31', '2026-06-30'],
              dtype='datetime64[ns]', freq='M')


In [27]:
ts_ms = pd.date_range(start = '2024-01-01', end = None, periods = 30, freq = 'Q')
print(ts_ms)

DatetimeIndex(['2024-03-31', '2024-06-30', '2024-09-30', '2024-12-31',
               '2025-03-31', '2025-06-30', '2025-09-30', '2025-12-31',
               '2026-03-31', '2026-06-30', '2026-09-30', '2026-12-31',
               '2027-03-31', '2027-06-30', '2027-09-30', '2027-12-31',
               '2028-03-31', '2028-06-30', '2028-09-30', '2028-12-31',
               '2029-03-31', '2029-06-30', '2029-09-30', '2029-12-31',
               '2030-03-31', '2030-06-30', '2030-09-30', '2030-12-31',
               '2031-03-31', '2031-06-30'],
              dtype='datetime64[ns]', freq='Q-DEC')


### 년월일 분리와 시차 특성을 갖는 데이터를 생성

In [48]:
df = pd.read_csv('./data/stock-data.csv')
# df.info()

df['NewDate'] = pd.to_datetime(df['Date'])
# df.info()
# print(df.head())

# #년도만 추출
# print(df['NewDate'].dt.year.head())
# #월만 추출
# print(df['NewDate'].dt.month.head())

#날짜를 인덱스로 갖는 Series를 생성
ts = pd.Series(np.random.randn(20), index = df['NewDate'])
print(ts.tail())
print("==========================================")
print(ts.shift(-1).tail()) # 간격이 밀려서 들어옴
print()
print(ts.head())
print("==========================================")
print(ts.shift(1).head()) # 간격이 밀려서 들어옴
print()
print(ts.head())
print("==========================================")
print(ts.shift(2).head()) # 간격이 밀려서 들어옴

NewDate
2018-06-08    0.315340
2018-06-07   -0.416292
2018-06-05   -0.123046
2018-06-04    0.306806
2018-06-01   -0.020717
dtype: float64
NewDate
2018-06-08   -0.416292
2018-06-07   -0.123046
2018-06-05    0.306806
2018-06-04   -0.020717
2018-06-01         NaN
dtype: float64

NewDate
2018-07-02    1.312098
2018-06-29    0.452880
2018-06-28    1.337149
2018-06-27   -1.121675
2018-06-26    1.100402
dtype: float64
NewDate
2018-07-02         NaN
2018-06-29    1.312098
2018-06-28    0.452880
2018-06-27    1.337149
2018-06-26   -1.121675
dtype: float64

NewDate
2018-07-02    1.312098
2018-06-29    0.452880
2018-06-28    1.337149
2018-06-27   -1.121675
2018-06-26    1.100402
dtype: float64
NewDate
2018-07-02         NaN
2018-06-29         NaN
2018-06-28    1.312098
2018-06-27    0.452880
2018-06-26    1.337149
dtype: float64


### 결측치 대체

In [52]:
time_index = pd.date_range('01/01/2024', periods = 5, freq = 'M')
dataframe = pd.DataFrame(index = time_index)
#결측치 생성
dataframe['Sales'] = [1, 2, np.nan, np.nan, 5]
print(dataframe)

#결측치 채우기 - 앞이나 뒤의 값으로 채우기
print(dataframe.ffill())
print(dataframe.bfill())


            Sales
2024-01-31    1.0
2024-02-29    2.0
2024-03-31    NaN
2024-04-30    NaN
2024-05-31    5.0
            Sales
2024-01-31    1.0
2024-02-29    2.0
2024-03-31    2.0
2024-04-30    2.0
2024-05-31    5.0
            Sales
2024-01-31    1.0
2024-02-29    2.0
2024-03-31    5.0
2024-04-30    5.0
2024-05-31    5.0
            Sales
2024-01-31    1.0
2024-02-29    2.0
2024-03-31    3.0
2024-04-30    4.0
2024-05-31    5.0
               Sales
2024-01-31  1.000000
2024-02-29  2.000000
2024-03-31  3.040158
2024-04-30  4.018418
2024-05-31  5.000000


In [59]:
#보간 - 이전과 이후 데이터를 가지고 예측을 해서 설정 - 선형으로 예측
#실제 작업을 할 때는 데이터의 분포를 확인을 해서 선형인지 비선형인지 결정
print(dataframe.interpolate())
#비선형으로 예측
print(dataframe.interpolate(method = 'quadratic'))

from datetime import datetime
# 중간에 날짜가 비어 있는 경우에는 앞 뒤의 날짜를 확인해서
# 다음 날짜가 맞는지 아닌지 확인해서 값을 기반으로 할지 날짝를 기반으로 할지 결정
dates = [datetime(2024, 1, 1), datetime(2024, 1, 2), datetime(2024, 1, 3), 
         datetime(2024, 1, 6), datetime(2024, 1, 7)]

dataframe = pd.DataFrame(index = dates)
dataframe['Sales'] = [1, 2, 3, np.nan, 7]

print(dataframe.interpolate(method = 'time'))# 이 method는 시간 흐름을 고려하는 뜻

            Sales
2024-01-01    1.0
2024-01-02    2.0
2024-01-03    3.0
2024-01-06    5.0
2024-01-07    7.0
            Sales
2024-01-01    1.0
2024-01-02    2.0
2024-01-03    3.0
2024-01-06    6.0
2024-01-07    7.0
            Sales
2024-01-01    1.0
2024-01-02    2.0
2024-01-03    3.0
2024-01-06    6.0
2024-01-07    7.0


### resampling - 데이터의 빈도를 늘리거나 줄이는 것 -일반적인 방법과 다른 점은 시계열을 주기가 있단느 점

In [65]:
range = pd.date_range('2024-02-01', '2024-02-02', freq='2min')
df = pd.DataFrame(index = range)[:20]
df['price'] = np.random.randint(low =10, high = 100, size =20)
df['amount'] = np.random.randint(low =1, high = 5, size =20)
print(df)

                     price  amount
2024-02-01 00:00:00     64       1
2024-02-01 00:02:00     49       2
2024-02-01 00:04:00     16       3
2024-02-01 00:06:00     71       3
2024-02-01 00:08:00     31       3
2024-02-01 00:10:00     11       1
2024-02-01 00:12:00     91       4
2024-02-01 00:14:00     72       3
2024-02-01 00:16:00     63       2
2024-02-01 00:18:00     63       3
2024-02-01 00:20:00     30       4
2024-02-01 00:22:00     95       4
2024-02-01 00:24:00     45       4
2024-02-01 00:26:00     26       3
2024-02-01 00:28:00     94       4
2024-02-01 00:30:00     30       3
2024-02-01 00:32:00     15       2
2024-02-01 00:34:00     39       3
2024-02-01 00:36:00     64       3
2024-02-01 00:38:00     80       2


In [71]:
# 다운 샘플링  - 시간 간격을 10분으로 조정 : 4개의 데이터로 변경
# print(df.price.resample('10T').first())
#시계열 데이터의 경우시간 별 집계를 수행하는 방법
print(df.price.resample('10T').sum())

#업 샘플링
# print(df.price.resample('1T').first())

2024-02-01 00:00:00    231
2024-02-01 00:10:00    300
2024-02-01 00:20:00    290
2024-02-01 00:30:00    228
Freq: 10T, Name: price, dtype: int32


### 이동평균 계산

In [74]:
#2024년 1월 1일 부터 월 단위로 5개의 데이터를 생성
time_index = pd.date_range('01/01/2024', periods = 5, freq = "M")

#위의 데이터를 인덱스로 해서 시계열 DataFrame을 생성
#pandas 에서는 인덱스가 시간인 경우 또는 일정한 패턴인 경우를 시계열로 판정
dataframe = pd.DataFrame(index = time_index)

dataframe['Stock_Price'] = [1, 2, 3, 4, 5]

#단순이동 평균 계산
print(dataframe.rolling(window = 2).mean())

#지수 이동 평균 계산
print(dataframe.ewm(span = 2).mean())

            Stock_Price
2024-01-31          NaN
2024-02-29          1.5
2024-03-31          2.5
2024-04-30          3.5
2024-05-31          4.5
            Stock_Price
2024-01-31     1.000000
2024-02-29     1.750000
2024-03-31     2.615385
2024-04-30     3.550000
2024-05-31     4.520661


## 윈도우 출력

In [76]:
import cv2

ModuleNotFoundError: No module named 'cv2'